### ISSUE TITLE
Admin Yetkileri

### ISSUE THREAD

**Issue by MuhammetDilmac** [ADEOSec/FFA#3]
Admin kullanıcıları kendi haklarını yükseltebiliyor.

**Comment by xsuperbug** [comment]
Kendi bugını kendi buluyor adam. Maşallah :)

**Comment by MuhammetDilmac** [comment]
Önemsemiyordum @xsuperbug abi zaten biz bize yapıyoruz diye :) Ama madem açtık o zaman bunu insanlar bilsinler :) 2-3 güne bug fix geçerim zaten :)
